[AutoBleem]
Aspect=false
# for date time format choices see: http://www.cplusplus.com/reference/ctime/strftime/
Datetimeformat=%F %I:%M:%S %p
Mip=false
Nomusic=false
Origames=true
Pcsx=bleemsync
Retroarch=true
Theme=ab2
